version: '3.8'

services:
  nginx:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./fail2ban/jail.local:/etc/fail2ban/jail.local
      - ./fail2ban/filter.d/nginx-http-auth.conf:/etc/fail2ban/filter.d/nginx-http-auth.conf
      - ./scripts/monitor_logs.py:/usr/local/bin/monitor_logs.py
